###################################################################
#                                                                 #
#                         MENU ITEM CREATION                      #
#                                                                 #
###################################################################
#
# items:                  <-- Defines the section where custom items will be configured. -->
#   spawn:                <-- Item identifier that could be used in other parts of the code to reference the item. -->
#   display-name: BED     <-- Sets the item material in the game -->
#   lore:                 <-- Configures the item description -->
#      - Return to spawn  <-- Example of lore -->
#   slot: 1               <-- Sets the item's position in the player's inventory -->
#
###################################################################
#                             OPTIONAL                            #
###################################################################
#
#   data: {ID}            <-- Defines a specific material variation -->
#   amount: 1             <-- Defines the quantity of items for the player's inventory -->
#
###################################################################

#
# MENU BUILD
#
items:
  info:
    material: IRON_PICKAXE
    display-name: "§bBuild Menu"
    slot: 4

  checkpoint:
    material: EMERALD
    display-name: "§aSet new checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Set your own checkpoint."
    slot: 20

  return-to-checkpoint:
    material: INK_SACK
    data: 1
    amount: 1
    display-name: "§cBack to checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Return to your previous checkpoint."
    slot: 21

  adventure:
    material: DIAMOND
    display-name: "§bJump Mode §8[§7Right-Click§8]"
    lore:
      - "§7Enable Jump Mode. You can test your"
      - "§7parkour map with this item. especially gimmick"
      - "§7maps."
    slot: 22

  sword:
    material: DIAMOND_SWORD
    display-name: "§6Setup coordinates"
    lore:
      - "§7Use this to setup precise coordinates."
    slot: 23

  finish:
    material: GOLD_PLATE
    display-name: "§6Finish Plate"
    lore:
      - "§7You can also set finish with normal gold"
      - "§7pressure plate."
    slot: 24

  hide:
    material: INK_SACK
    data: 10
    amount: 1
    display-name: "§aHide player §8[§7Right-Click§8]"
    lore:
      - "§7Hide all players."
    slot: 25

  show:
    material: INK_SACK
    data: 8
    amount: 1
    display-name: "§7Show players §8[§7Right-Click§8]"
    lore:
      - "§7Show all players."
    slot: 25

  fly:
    material: FEATHER
    display-name: "§aEnable Fly §8[§7Right-Click§8]"
    lore:
      - "§7Enable fly with this item."
    slot: 29

  fly-disable:
    material: FEATHER
    display-name: "§7Disable Fly §8[§7Right-Click§8]"
    lore:
      - "§7Disable fly with this item."

  select-map:
    material: NETHER_STAR
    display-name: "§dMain Menu"
    lore:
      - "§7Use this item to select the map you want to go and practice."
    slot: 30

  teleport-player:
    material: NETHER_STAR
    display-name: "§bTeleport to players §8[§7Right-Click§8]"
    lore:
      - "Teleport to other players!"
    slot: 31

  spectate-enable:
    material: EYE_OF_ENDER
    display-name: "§aSpectate Mode §8[§7Right-Click§8]"
    lore:
      - "§7Enable spectate mode with this item."
    slot: 32

  spectate-disable:
    material: ENDER_PEARL
    display-name: "§cDisable Spectate Mode §8[§7Right-Click§8]"
    lore:
      - "§7Disable spectate mode with this item."
    slot: 33

  disable-practice:
    material: MAGMA_CREAM
    display-name: "§cDisable practice mode §8[§7Right-Click§8]"
    lore:
      - "§7Disable practice mode with this item. You can also"
      - "§7disable practice mode with /unprac command!"
    slot: 34

  practice-mode:
    material: GOLD_INGOT
    display-name: "§bPractice Mode §8[§7Right-Click§8]"
    lore:
      - "§7Enable practice mode with this item."
    slot: 35

  prac-checkpoint:
    material: SLIME_BALL
    display-name: "§eReturn to Checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Return to your previous checkpoint."
    slot: 36

#
# JUMP MODE INVENTORY
#
JumpMode:
  checkpoint:
    material: EMERALD
    display-name: "§aSet new checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Set your own checkpoint."
    slot: 3

  prac-checkpoint:
    material: SLIME_BALL
    display-name: "§eReturn to Checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Return to your previous checkpoint."
    slot: 36

  adventure:
    material: DIAMOND
    display-name: "§bJump Mode §8[§7Right-Click§8]"
    lore:
      - "§7Enable Jump Mode. You can test your parkour map with this item, especially gimmick maps."
    slot: 9

  sword:
    material: DIAMOND_SWORD
    display-name: "§6Diamond Sword"
    lore:
      - "§7Use to find coordinates more accurately."
    slot: 2

  hide:
    material: INK_SACK
    data: 10
    amount: 1
    display-name: "§aHide player §8[§7Right-Click§8]"
    lore:
      - "§7Hide all players."
    slot: 25

  show:
    material: INK_SACK
    data: 8
    amount: 1
    display-name: "§7Show players §8[§7Right-Click§8]"
    lore:
      - "§7Show all players."
    slot: 25

#
# SPECTATOR MODE INVENTORY
#
spectator:
  checkpoint:
    material: EMERALD
    display-name: "§aSet new checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Set your own checkpoint."
    slot: 2

  prac-checkpoint:
    material: SLIME_BALL
    display-name: "§eReturn to Checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Return to your previous checkpoint."
    slot: 36

  sword:
    material: DIAMOND_SWORD
    display-name: "§6Diamond Sword"
    lore:
      - "§7Use to find coordinates more accurately."
    slot: 1

  fly:
    material: FEATHER
    display-name: "§aEnable Fly §8[§7Right-Click§8]"
    lore:
      - "§7Enable fly with this item."
    slot: 7

  teleport-player:
    material: NETHER_STAR
    display-name: "§bTeleport to players §8[§7Right-Click§8]"
    lore:
      - "Teleport to other players!"
    slot: 4

  spectate-disable:
    material: ENDER_PEARL
    display-name: "§cDisable Spectate Mode §8[§7Right-Click§8]"
    lore:
      - "§7Disable spectate mode with this item."
    slot: 6

  practice-mode:
    material: GOLD_INGOT
    display-name: "§bPractice Mode §8[§7Right-Click§8]"
    lore:
      - "§7Enable practice mode with this item."
    slot: 8

#
# PRACTICE MODE INVENTORY
#
practice:
  checkpoint:
    material: EMERALD
    display-name: "§aSet new checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Set your own checkpoint."
    slot: 2

  prac_checkpoint:
    material: SLIME_BALL
    display-name: "§eReturn to Checkpoint §8[§7Right-Click§8]"
    lore:
      - "§7Return to your previous checkpoint."
    slot: 36

  sword:
    material: DIAMOND_SWORD
    display-name: "§6Diamond Sword"
    lore:
      - "§7Use to find coordinates more accurately."
    slot: 1

  spectate-enable:
    material: EYE_OF_ENDER
    display-name: "§aSpectate Mode §8[§7Right-Click§8]"
    lore:
      - "§7Enable spectate mode with this item."
    slot: 32

  disable-practice:
    material: MAGMA_CREAM
    display-name: "§cDisable practice mode §8[§7Right-Click§8]"
    lore:
      - "§7Disable practice mode with this item. You can also"
      - "§7disable practice mode with /unprac command!"
    slot: 8

  hide:
    material: INK_SACK
    data: 10
    amount: 1
    display-name: "§aHide player §8[§7Right-Click§8]"
    lore:
      - "§7Hide all players."
    slot: 7